/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.wesleyhome.koin.aws.lambda

import kotlin.reflect.KClass

@Target(AnnotationTarget.CLASS)
annotation class LambdaHandler(
  val moduleClasses: Array<KClass<*>> = [],
  val name: String = "",
  val packageName: String = ""
)
